openapi: 3.0.0

info:
  title: Temporal time series API
  description: API documentation for the Temporal sime series micro service.
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Local development server

paths:
  /:
    get:
      summary: Returns a greeting message
      operationId: helloWorld
      responses:
        "200":
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: Hello World!
  /hello:
    get:
      summary: Returns a greeting message
      operationId: helloWorld
      responses:
        "200":
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: Hello World!
  /api:
    get:
      summary: Returns a greeting message
      operationId: helloWorld
      responses:
        "200":
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: Hello World!
  /api/hello:
    get:
      summary: Returns a greeting message
      operationId: helloWorld
      responses:
        "200":
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: Hello World!
