services:
  publish_subscribe_node:
    image: publish_subscribe_node
    build:
      context: ./ros2/src/publish_subscribe_node
      dockerfile: Dockerfile
    container_name: publish_subscribe_node
    environment:
      - RCUTILS_LOGGING_USE_STDERR=0 # Logs STDERR
      - RCUTILS_LOGGING_USE_STDOUT=0 # Logs STDOUT
      - RCUTILS_LOGGING_IMPLEMENTATION=rcutils_logging_file
      - ROS_HOME=/ros2_ws/.ros
    volumes:
      - ./ros2/src/publish_subscribe_node/Logs:/ros_logs_backup
    tmpfs:
      - /ros2_ws/.ros/log # To RAM
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M
        reservations:
          cpus: "1"
          memory: 200M