services:
  #talker:
   # build:
    #  context: .
     # dockerfile: Dockerfile
    #image: my/ros:app
    #command: ros2 run demo_nodes_cpp talker
    #networks:
     # - ros-net

  #listener:
   # build:
    #  context: .
     # dockerfile: Dockerfile
   # image: my/ros:app
    #command: ros2 run demo_nodes_py listener
   # networks:
    #  - ros-net
  my_node:
    build:
      context: src/temporal_execution
      dockerfile: Dockerfile  
    image: my/ros:app
    command: bash -c "source /opt/ros/jazzy/setup.bash && source install/setup.bash && ros2 run temporal_execution loop_node"
    networks:
      - ros-net
    volumes:
      - ./src:/ros2_ws/src 
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 200M

networks:
  ros-net:
    driver: bridge
