services:
  system_controller:
    image: system_controller
    build:
      context: ./ros2/src/system_controller
      dockerfile: Dockerfile
    container_name: system_controller
    environment:
      - RCUTILS_LOGGING_USE_STDERR=0 # Logs STDERR
      - RCUTILS_LOGGING_USE_STDOUT=0 # Logs STDOUT
      - RCUTILS_LOGGING_IMPLEMENTATION=rcutils_logging_file
      - ROS_HOME=/ros2_ws/.ros
    volumes:
      - ./ros2/src/system_controller/Logs:/ros_logs_backup
    tmpfs:
      - /ros2_ws/.ros/log # To RAM
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M
        reservations:
          cpus: "1"
          memory: 200M