services:
  pub_and_sub:
    image: pub_and_sub
    build:
      context: ./ros2/src/pub_and_sub
      dockerfile: Dockerfile
    container_name: pub_and_sub
    environment:
      - RCUTILS_LOGGING_USE_STDERR=0 # Logs STDERR
      - RCUTILS_LOGGING_USE_STDOUT=0 # Logs STDOUT
      - RCUTILS_LOGGING_IMPLEMENTATION=rcutils_logging_file
      - ROS_HOME=/ros2_ws/.ros
    volumes:
      - ./ros2/src/pub_and_sub/Logs:/ros_logs_backup
    tmpfs:
      - /ros2_ws/.ros/log # To RAM
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M
        reservations:
          cpus: "1"
          memory: 200M